/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityDropdown: typeof import('./src/components/ActivityDropdown.vue')['default']
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    CheckTreeSelect: typeof import('./src/components/CheckTreeSelect.vue')['default']
    ConfirmModal: typeof import('./src/components/ConfirmModal.vue')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    DateRangePicker: typeof import('./src/components/DateRangePicker.vue')['default']
    DropdownComponent: typeof import('./src/components/DropdownComponent.vue')['default']
    HelperCsvComponent: typeof import('./src/components/Promo/HelperCsvComponent.vue')['default']
    InputNumber: typeof import('./src/components/InputNumber.vue')['default']
    InputText: typeof import('./src/components/InputText.vue')['default']
    InputTextAppend: typeof import('./src/components/InputTextAppend.vue')['default']
    InputTextPrepend: typeof import('./src/components/InputTextPrepend.vue')['default']
    LanguageSwitcher: typeof import('./src/components/LanguageSwitcher.vue')['default']
    LayoutComponent: typeof import('./src/components/LayoutComponent.vue')['default']
    ModalComponent: typeof import('./src/components/ModalComponent.vue')['default']
    NavBar: typeof import('./src/components/NavBar/NavBar.vue')['default']
    NavBarItem: typeof import('./src/components/NavBar/NavBarItem.vue')['default']
    OperatorAutoComplete: typeof import('./src/components/OperatorAutoComplete.vue')['default']
    OperatorTreeSelect: typeof import('./src/components/OperatorTreeSelect.vue')['default']
    OTPInput: typeof import('./src/components/OTPInput.vue')['default']
    PageHeaderComponent: typeof import('./src/components/PageHeaderComponent.vue')['default']
    PaginationNav: typeof import('./src/components/WLSTable/PaginationNav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPanelComponent: typeof import('./src/components/SearchPanelComponent.vue')['default']
    TextEditor: typeof import('./src/components/TextEditor.vue')['default']
    ToastComponent: typeof import('./src/components/ToastComponent.vue')['default']
    ToggleSwitch: typeof import('./src/components/ToggleSwitch.vue')['default']
    TooltipWrapper: typeof import('./src/components/TooltipWrapper.vue')['default']
    TreeView: typeof import('./src/components/TreeView.vue')['default']
    UploadAnnouncementComponent: typeof import('./src/components/Lobby/UploadAnnouncementComponent.vue')['default']
    UploadImageMediaComponent: typeof import('./src/components/Lobby/UploadImageMediaComponent.vue')['default']
    UploadImagePromoComponent: typeof import('./src/components/Promo/UploadImagePromoComponent.vue')['default']
    UploadOperatorsComponent: typeof import('./src/components/Promo/UploadOperatorsComponent.vue')['default']
    UploadPlayersComponent: typeof import('./src/components/Promo/UploadPlayersComponent.vue')['default']
    WLSColumnHeader: typeof import('./src/components/WLSTable/WLSColumnHeader.vue')['default']
    WLSColumnHeaderItem: typeof import('./src/components/WLSTable/WLSColumnHeaderItem.vue')['default']
    WLSRow: typeof import('./src/components/WLSTable/WLSRow.vue')['default']
    WLSRowColumn: typeof import('./src/components/WLSTable/WLSRowColumn.vue')['default']
    WLSTable: typeof import('./src/components/WLSTable/WLSTable.vue')['default']
    WLSTableHeaderContainer: typeof import('./src/components/WLSTable/WLSTableHeaderContainer.vue')['default']
  }
}
